services:
  mysql:
    image: mysql:8.0
    container_name: location_voitures_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: location_voitures
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d